/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VRouteImport } from './routes/_v'
import { Route as VIndexRouteImport } from './routes/_v.index'

const VRoute = VRouteImport.update({
  id: '/_v',
  getParentRoute: () => rootRouteImport,
} as any)
const VIndexRoute = VIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof VIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof VIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_v': typeof VRouteWithChildren
  '/_v/': typeof VIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/_v' | '/_v/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  VRoute: typeof VRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_v': {
      id: '/_v'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof VRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_v/': {
      id: '/_v/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof VIndexRouteImport
      parentRoute: typeof VRoute
    }
  }
}

interface VRouteChildren {
  VIndexRoute: typeof VIndexRoute
}

const VRouteChildren: VRouteChildren = {
  VIndexRoute: VIndexRoute,
}

const VRouteWithChildren = VRoute._addFileChildren(VRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  VRoute: VRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
