name: 'Deploy'

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install
        run: npm run setup
      - name: Lint
        run: npm run lint
      - name: Typecheck
        run: npm run typecheck
      - name: Convex
        env:
          CONVEX_DEPLOY_KEY: ${{ secrets.CONVEX_DEPLOY_KEY }}
          VITE_CONVEX_URL: ${{ secrets.VITE_CONVEX_URL }}
        run: npm run deploy
      - name: Deploy Build
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.PRTCL_HOST }}
          username: ${{ secrets.PRTCL_USERNAME }}
          password: ${{ secrets.PRTCL_PASSWORD }}
          port: ${{ secrets.PRTCL_PORT }}
          source: dist/*
          target: ${{ secrets.PRTCL_REMOTE_PATH }}
